<?php


namespace app\admin\controller;


use app\model\Article;
use think\facade\View;

class Articles extends BaseAdmin
{
    protected $articleService;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->articleService = app('articleService');
    }

    public function index() {
        $data = $this->articleService->getPagedAdmin();
        View::assign([
            'articles' => $data['articles'],
            'count' => $data['count']
        ]);
        return view();
    }

    public function search() {
        $title = input('title');
        $where = [
            ['title', 'like', '%' . $title . '%']
        ];
        $data = $this->articleService->getPagedAdmin($where);
        View::assign([
            'articles' => $data['articles'],
            'count' => $data['count']
        ]);
        return view('index');
    }

    public function delete()
    {
        $id = input('id');
        $result = Article::destroy($id);
        if ($result) {
            return json(['err' => '0','msg' => '删除成功']);
        } else {
            return json(['err' => '1','msg' => '删除失败']);
        }
    }

    public function deleteAll($ids){
        $ids = input('ids');
        $result = Article::destroy($ids);
        if ($result) {
            return json(['err' => '0','msg' => '删除成功']);
        } else {
            return json(['err' => '1','msg' => '删除失败']);
        }
    }
}